name: gradient_radio_button
description: A new Flutter project.

publish_to: "none"

version: 1.0.2+2

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
